apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q9ngyxbwd-go 
  janus-idp.io/tekton: q9ngyxbwd-go
  backstage.io/kubernetes-id: q9ngyxbwd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q9ngyxbwd-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml